services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    stdin_open: true
    tty: true
    init: true
    stop_signal: SIGINT