package de.busesteinkamp.domain.events

import java.time.Instant
import java.util.*

/**
 * Domain Event published when content is generated by an AI generator.
 * This event tracks content generation activities in the system.
 */
data class ContentGeneratedEvent(
    override val eventId: UUID = UUID.randomUUID(),
    override val occurredAt: Instant = Instant.now(),
    override val actorId: String,
    override val createdBy: String = "ContentGenerator",
    val contentId: UUID,
    val generatorType: String,
    val contentType: String,
    val contentSize: Long,
    val generationParameters: Map<String, String> = emptyMap()
) : DomainEvent {
    override val eventType: String = "ContentGenerated"
    
    companion object {
        /**
         * Factory method to create a ContentGeneratedEvent
         */
        fun create(
            contentId: UUID,
            generatorType: String,
            contentType: String,
            contentSize: Long,
            generationParameters: Map<String, String> = emptyMap(),
            actorId: String = "system"
        ): ContentGeneratedEvent {
            return ContentGeneratedEvent(
                contentId = contentId,
                generatorType = generatorType,
                contentType = contentType,
                contentSize = contentSize,
                generationParameters = generationParameters,
                actorId = actorId
            )
        }
    }
} 